/*
 * Demo.java
 *
 * Created on __DATE__, __TIME__
 */
package com.view;

import com.xl.file.FileService;

import java.awt.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 * @author __USER__
 */
public class Demo extends javax.swing.JFrame {
    private int[] num = new int[2];
    private int count = -1;
    // GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // GEN-END:initComponents
    private javax.swing.JTextArea jTextArea1;

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);
        jButton1.setText("\u786e\u5b9a");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addGap(64, 64, 64).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(63, 63, 63).addComponent(jButton1).addContainerGap(95, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(70, 70, 70).addComponent(jButton1))
                      .addGroup(layout.createSequentialGroup().addGap(41, 41, 41).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(329, Short.MAX_VALUE)));
        pack();
    }// </editor-fold>

    /**
     * @param evt 17,2,10,1
     */
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {
        count++;
        if (count > 1) {
            count = 0;
        }
        num[count] = evt.getKeyCode();
        if ((num[0] == 10 && num[1] == 17) || (num[0] == 17 && num[1] == 10)) {
            jButton1.doClick();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        FileService service = new FileService();
        String content = jTextArea1.getText();
        try {
            URI uri = new URI(content);
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException e) {
        } catch (IOException e) {
        }
    }
    // End of variables declaration//GEN-END:variables
}
